Myname= input ("What is your name")
print ("Cool, that's a cool name")
print(Myname)
Myfood= input ("what is your favorite food")
print ("Yum! That sounds delicious!")
Mymusic= input ("What is your favorite music")
print (Mymusic)
print ("seems to be very energizing")
Mylanguage= input ("What is your favorite programming language")
print (Mylanguage)
print ("Yay! Of course you like Python")
print ("It was very nice getting to know you!")
print ("You are")
print (Myname)
print ("You're probably super hungry for")
print (Myfood)
print ("And you seem very tuned into")
print (Mymusic)
print ("music!") 
print ("Also, thank you so much for sharing your favorite programming language. It deeply touched my heart when you said it was")
print (Mylanguage)
print ("Hope you have a very awesome day. Farewell!")