print ("""Howdy! In the mean time, we would like to create a new menu recipe, and I'm sure you'll want to help us out! So, let's get right into it!""")
food= input ("Name a food")
plant= input ("Name a plant")
cooking= input ("Name a method of cooking")
burnedfood= input ("Name a word to describe burned food")
item= input ("Name a household item")
print()
print("Thank you so much, my friend! Here's what we've got:")
print("MENU")
print(food, "and", plant, cooking, "with sausage", burnedfood, "on a roof of", item, "s")