print("Hi, my friend! Today, we're going to create a poster about what your profile, and then post it on the school website! So, you ready? Of course you are! Then let's get right into it!")
print()
myName= input ("What is your name?")
enjoy= input("What is something that you like?")
hate= input("What is something that you hate?")
freetime= input("What do you like to do in your free time?")
favbook= input("What is your favorite book?")
favmovie= input("What movie do you like?")
favhobby= input("What is your most beloved hobby?")
favmusic= input("What type of music do you enjoy?")
print()
print("Wow", myName, enjoy, "and", freetime, "seems to be your true passions! However, I feel sorry for you that", hate, "is something you don't like, I feel you! Now go outside in the fresh air and do some", favhobby, "or sit on the cozy couch in a rainy evening and read", favbook, "watch", favmovie, "or simply lie down and listen to", favmusic, "All of those are amazing ways to spend your time!")